// This code is generated by AI for quick understanding of concept and fast prototyping, will be subject to rewrite later

/*
 * Question-3.cc
 * -------------
 * Given a CSV of unordered cone coordinates (metres, local to car at origin),
 * generate a CSV of midline waypoints spaced <= 0.5 m apart.
 *
 * Core fix vs previous version:
 *   Raw midpoints sorted by greedy-NN tangle badly on complex tracks.
 *   Instead, we build a GRAPH where two midpoint nodes are adjacent iff
 *   their parent Delaunay edges share a triangle.  A DFS walk on this
 *   graph respects triangulation topology → no crossings even on hairpins.
 *
 * Algorithm:
 *   1.  Load cones
 *   2.  Bowyer-Watson Delaunay triangulation
 *   3.  Per triangle: collect cross-track edges (length in [minW,maxW])
 *       → each edge becomes one midpoint node
 *   4.  Two nodes from the same triangle → graph edge (adj list, degree ≤ 3)
 *   5.  DFS walk with heading-bias from node nearest origin
 *   6.  Catmull-Rom spline resampled at ≤ 0.5 m
 *   7.  Write output CSV
 *
 * Compile:
 *   g++ -std=c++17 -O2 -o Question-3 Question-3.cc -lm
 * Usage:
 *   ./Question-3 cones.csv waypoints.csv
 */

#include <algorithm>
#include <cmath>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

/* ══════════════════════════════════════════════════════════════════════════
 * GEOMETRY
 * ══════════════════════════════════════════════════════════════════════════ */

struct Point { double x=0, y=0; };

static constexpr double kEps = 1e-9;

static Point  operator+(Point a, Point b)  { return {a.x+b.x, a.y+b.y}; }
static Point  operator-(Point a, Point b)  { return {a.x-b.x, a.y-b.y}; }
static Point  operator*(Point a, double s) { return {a.x*s,   a.y*s};   }
static Point  operator/(Point a, double s) { return {a.x/s,   a.y/s};   }
static double dot  (Point a, Point b) { return a.x*b.x+a.y*b.y; }
static double norm (Point a)          { return std::sqrt(dot(a,a)); }
static double dist (Point a, Point b) { return norm(a-b); }

/* ══════════════════════════════════════════════════════════════════════════
 * CSV I/O
 * ══════════════════════════════════════════════════════════════════════════ */

static std::vector<Point> readCsv(const std::string& path) {
    std::ifstream in(path);
    if (!in.is_open()) throw std::runtime_error("Cannot open: "+path);
    std::vector<Point> pts;
    std::string line;
    bool first=true;
    while (std::getline(in,line)) {
        if (line.empty()) continue;
        if (first) {
            first=false;
            if (line.find('x')!=std::string::npos ||
                line.find('X')!=std::string::npos) continue;
        }
        std::stringstream ss(line);
        std::string sx,sy;
        if (!std::getline(ss,sx,',') || !std::getline(ss,sy,',')) continue;
        try { pts.push_back({std::stod(sx),std::stod(sy)}); } catch(...) {}
    }
    return pts;
}

static void writeCsv(const std::string& path, const std::vector<Point>& pts) {
    std::ofstream out(path);
    if (!out.is_open()) throw std::runtime_error("Cannot write: "+path);
    out << std::fixed << std::setprecision(9) << "x,y\n";
    for (auto& p : pts) out << p.x << ',' << p.y << '\n';
}

/* ══════════════════════════════════════════════════════════════════════════
 * BOWYER-WATSON DELAUNAY TRIANGULATION
 * ══════════════════════════════════════════════════════════════════════════ */

struct Tri { int a,b,c; };

static std::vector<Tri> delaunay(const std::vector<Point>& pts) {
    const int n=(int)pts.size();
    if (n<3) return {};

    std::vector<Point> all=pts;
    double x0=pts[0].x,y0=pts[0].y,x1=x0,y1=y0;
    for (auto& p:pts){x0=std::min(x0,p.x);y0=std::min(y0,p.y);
                       x1=std::max(x1,p.x);y1=std::max(y1,p.y);}
    double big=std::max(x1-x0,y1-y0)*20.0;
    double cx=(x0+x1)*0.5, cy=(y0+y1)*0.5;
    int s0=n,s1=n+1,s2=n+2;
    all.push_back({cx-big, cy-big});
    all.push_back({cx,     cy+big});
    all.push_back({cx+big, cy-big});

    std::vector<Tri> tris={{s0,s1,s2}};

    auto inCC=[&](const Tri& T, Point p){
        Point A=all[T.a],B=all[T.b],C=all[T.c];
        double ax=B.x-A.x,ay=B.y-A.y,bx=C.x-A.x,by=C.y-A.y;
        double D=2*(ax*by-ay*bx);
        if (std::fabs(D)<kEps) return false;
        double ux=(by*(ax*ax+ay*ay)-ay*(bx*bx+by*by))/D;
        double uy=(ax*(bx*bx+by*by)-bx*(ax*ax+ay*ay))/D;
        double dx=p.x-(A.x+ux),dy=p.y-(A.y+uy);
        return dx*dx+dy*dy < ux*ux+uy*uy-kEps;
    };

    struct Edge{int u,v;};

    for (int p=0;p<n;++p){
        std::vector<int> bad;
        for (int t=0;t<(int)tris.size();++t)
            if (inCC(tris[t],all[p])) bad.push_back(t);

        std::vector<Edge> bnd;
        for (int bi:bad){
            Edge es[3]={{tris[bi].a,tris[bi].b},
                        {tris[bi].b,tris[bi].c},
                        {tris[bi].c,tris[bi].a}};
            for (auto& e:es){
                bool shared=false;
                for (int bj:bad){
                    if (bj==bi) continue;
                    auto& U=tris[bj];
                    if ((e.u==U.a||e.u==U.b||e.u==U.c)&&
                        (e.v==U.a||e.v==U.b||e.v==U.c)){shared=true;break;}
                }
                if (!shared) bnd.push_back(e);
            }
        }
        std::vector<Tri> kept;
        for (int t=0;t<(int)tris.size();++t)
            if (std::find(bad.begin(),bad.end(),t)==bad.end())
                kept.push_back(tris[t]);
        tris=std::move(kept);
        for (auto& e:bnd) tris.push_back({e.u,e.v,p});
    }

    std::vector<Tri> res;
    for (auto& T:tris)
        if (T.a<n&&T.b<n&&T.c<n) res.push_back(T);
    return res;
}

/* ══════════════════════════════════════════════════════════════════════════
 * BUILD CENTRELINE GRAPH
 *
 * Each Delaunay edge whose length ∈ [minW,maxW] becomes a midpoint node.
 * Two nodes sharing a parent triangle are connected by a graph edge.
 * This gives a degree-≤3 planar graph that traces the centreline.
 * ══════════════════════════════════════════════════════════════════════════ */

struct Graph {
    std::vector<Point>           nodes;
    std::vector<std::vector<int>> adj;
};

static Graph buildGraph(const std::vector<Point>& cones,
                        const std::vector<Tri>&   tris,
                        double minW, double maxW)
{
    auto key=[](int u,int v)->std::pair<int,int>{
        return u<v?std::make_pair(u,v):std::make_pair(v,u);};

    std::map<std::pair<int,int>,int> edgeNode;
    std::vector<Point> nodes;

    auto getNode=[&](int u,int v)->int{
        double d=dist(cones[u],cones[v]);
        if (d<minW||d>maxW) return -1;
        auto k=key(u,v);
        auto it=edgeNode.find(k);
        if (it!=edgeNode.end()) return it->second;
        int id=(int)nodes.size();
        edgeNode[k]=id;
        nodes.push_back((cones[u]+cones[v])/2.0);
        return id;
    };

    std::set<std::pair<int,int>> adjSet;
    for (auto& T:tris){
        int e[3][2]={{T.a,T.b},{T.b,T.c},{T.c,T.a}};
        int ids[3];
        for (int i=0;i<3;i++) ids[i]=getNode(e[i][0],e[i][1]);
        for (int i=0;i<3;i++){
            if (ids[i]<0) continue;
            for (int j=0;j<3;j++){
                if (i==j||ids[j]<0) continue;
                adjSet.insert(key(ids[i],ids[j]));
            }
        }
    }

    Graph G;
    G.nodes=std::move(nodes);
    G.adj.resize(G.nodes.size());
    for (auto& p:adjSet){
        G.adj[p.first].push_back(p.second);
        G.adj[p.second].push_back(p.first);
    }
    return G;
}

/* ══════════════════════════════════════════════════════════════════════════
 * DFS WALK — topology-aware ordering, no tangling
 * ══════════════════════════════════════════════════════════════════════════ */

static std::vector<Point> walkGraph(const Graph& G, double maxGap=5.0){
    const int n=(int)G.nodes.size();
    if (n==0) return {};

    // Nearest to origin
    int start=0; double best=std::numeric_limits<double>::max();
    for (int i=0;i<n;i++){double d=dot(G.nodes[i],G.nodes[i]);if(d<best){best=d;start=i;}}

    std::vector<bool> visited(n,false);
    std::vector<int>  path;
    path.reserve(n);

    std::function<void(int,Point)> dfs=[&](int cur, Point heading){
        visited[cur]=true;
        path.push_back(cur);

        // Pick best unvisited neighbour: prefer forward + close
        int   best_nb=-1;
        double best_cost=std::numeric_limits<double>::max();
        for (int nb:G.adj[cur]){
            if (visited[nb]) continue;
            Point step=G.nodes[nb]-G.nodes[cur];
            double d=norm(step);
            Point dir=d>kEps?step/d:Point{1,0};
            double fwd=dot(heading,dir);
            double cost=d*(1.0-0.4*fwd);
            if (cost<best_cost){best_cost=cost;best_nb=nb;}
        }
        if (best_nb>=0){
            Point nh=G.nodes[best_nb]-G.nodes[cur];
            double h=norm(nh);
            dfs(best_nb, h>kEps?nh/h:heading);
        }
    };

    dfs(start,{1.0,0.0});

    // Bridge gaps to collect isolated sub-graphs
    while ((int)path.size()<n){
        int last=path.back();
        int nearest=-1; double minD=std::numeric_limits<double>::max();
        for (int i=0;i<n;i++){
            if (visited[i]) continue;
            double d=dist(G.nodes[last],G.nodes[i]);
            if (d<minD&&d<=maxGap){minD=d;nearest=i;}
        }
        if (nearest<0) break;
        Point nh=G.nodes[nearest]-G.nodes[last];
        double h=norm(nh);
        dfs(nearest, h>kEps?nh/h:Point{1,0});
    }

    std::vector<Point> res;
    res.reserve(path.size());
    for (int i:path) res.push_back(G.nodes[i]);
    return res;
}

/* ══════════════════════════════════════════════════════════════════════════
 * LAPLACIAN SMOOTHING
 * ══════════════════════════════════════════════════════════════════════════ */

static std::vector<Point> smooth(std::vector<Point> pts, int iters, double alpha){
    const int n=(int)pts.size();
    if (n<5) return pts;
    for (int it=0;it<iters;it++){
        std::vector<Point> nxt=pts;
        for (int i=0;i<n;i++){
            Point prev=pts[(i-1+n)%n],cur=pts[i],next=pts[(i+1)%n];
            nxt[i]=cur+((prev+next)/2.0-cur)*alpha;
        }
        pts=nxt;
    }
    return pts;
}

/* ══════════════════════════════════════════════════════════════════════════
 * CATMULL-ROM SPLINE
 * ══════════════════════════════════════════════════════════════════════════ */

static Point catmullRom(Point p0,Point p1,Point p2,Point p3,double t){
    return ((p1*2.0)+(p2-p0)*t
           +(p0*2.0-p1*5.0+p2*4.0-p3)*(t*t)
           +(p1*3.0-p0    -p2*3.0+p3)*(t*t*t))*0.5;
}

static std::vector<Point> spline(const std::vector<Point>& loop, double maxSpc=0.45){
    const int n=(int)loop.size();
    if (n<4) return loop;
    std::vector<Point> out;
    for (int i=0;i<n;i++){
        Point p0=loop[(i-1+n)%n],p1=loop[i],
              p2=loop[(i+1)%n], p3=loop[(i+2)%n];
        int steps=std::max(1,(int)std::ceil(dist(p1,p2)/maxSpc));
        for (int s=0;s<steps;s++)
            out.push_back(catmullRom(p0,p1,p2,p3,(double)s/steps));
    }
    return out;
}

/* ══════════════════════════════════════════════════════════════════════════
 * MAIN
 * ══════════════════════════════════════════════════════════════════════════ */

int main(int argc, char** argv){
    try {
        std::string inPath  = argc>1 ? argv[1] : "cones.csv";
        std::string outPath = argc>2 ? argv[2] : "waypoints.csv";

        auto cones = readCsv(inPath);
        std::cout << "Loaded " << cones.size() << " cones\n";
        if ((int)cones.size()<6) throw std::runtime_error("Too few cones.");

        std::cout << "Triangulating...\n";
        auto tris = delaunay(cones);
        std::cout << "  " << tris.size() << " triangles\n";

        // minW slightly below 3 m track-width minimum; maxW generous upper bound
        auto G = buildGraph(cones, tris, 2.5, 9.0);
        std::cout << "  " << G.nodes.size() << " centreline nodes\n";

        if ((int)G.nodes.size()<4)
            throw std::runtime_error("Too few centreline nodes.");

        std::cout << "Walking centreline graph...\n";
        auto raw = walkGraph(G, 5.0);
        std::cout << "  " << raw.size() << " ordered nodes\n";

        raw = smooth(raw, 4, 0.25);

        std::cout << "Interpolating spline...\n";
        auto wp = spline(raw, 0.45);
        wp = smooth(wp, 2, 0.1);

        if ((int)wp.size()<20)
            throw std::runtime_error("Too few waypoints generated.");

        writeCsv(outPath, wp);
        std::cout << "Written " << wp.size() << " waypoints -> " << outPath << "\n";
        return 0;
    }
    catch (const std::exception& e){
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }
}